# Generated by Django 6.0.2 on 2026-02-26 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Categor',
            new_name='Category',
        ),
    ]
